
import { ClassGroup, Student, Teacher, Score, BehaviorRating, Role, Session } from './types';

// Hardcoded Public Holidays (YYYY-MM-DD) until 2029
export const PUBLIC_HOLIDAYS = [
  // 2024
  '2024-01-01', '2024-02-10', '2024-03-29', '2024-04-10', '2024-05-01', '2024-06-17', '2024-08-09', '2024-10-31', '2024-12-25',
  // 2025
  '2025-01-01', '2025-01-29', '2025-03-31', '2025-04-18', '2025-05-01', '2025-06-06', '2025-08-09', '2025-10-20', '2025-12-25',
  // 2026
  '2026-01-01', '2026-02-17', '2026-04-03', '2026-05-01', '2026-05-26', '2026-08-09', '2026-11-08', '2026-12-25',
  // 2027
  '2027-01-01', '2027-02-06', '2027-03-26', '2027-05-01', '2027-05-15', '2027-08-09', '2027-10-29', '2027-12-25',
  // 2028
  '2028-01-01', '2028-01-26', '2028-04-14', '2028-05-01', '2028-06-02', '2028-08-09', '2028-10-18', '2028-12-25',
  // 2029
  '2029-01-01', '2029-02-13', '2029-03-30', '2029-05-01', '2029-05-20', '2029-08-09', '2029-11-06', '2029-12-25',
];

// Translations
export const TRANSLATIONS = {
  en: {
    loginTitle: 'Sign in to Insight EDU',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    loginButton: 'Sign in',
    loginFooter: 'Use demo credentials provided below.',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetSuccess: 'If an account exists for this email, you will receive a reset link shortly.',
    enterEmailForReset: 'Enter your email address to reset your password.',
    logout: 'Log out',
    dashboard: 'Dashboard',
    teachers: 'Teachers',
    students: 'Students',
    classes: 'Class',
    locations: 'Locations',
    reports: 'Reports',
    input: 'Score Input',
    rating: 'Class Rating',
    hq: 'HQ Portal',
    teacher: 'Teacher Portal',
    parent: 'Parent View',
    atRisk: 'At Risk',
    totalStudents: 'Total Students',
    avgPerformance: 'Avg Performance',
    sendReport: 'Send Report via WhatsApp',
    aiInsights: 'AI Insights',
    positiveTrend: 'Positive Trend',
    negativeTrend: 'Attention Needed',
    overall: 'Overall Summary',
    sendReportEmail: 'Send Report via Email',
    sendingReportEmail: 'Sending report...',
    reportEmailSuccess: 'Student report email sent.',
    reportEmailFailure: 'Unable to send report email.',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    name: 'Name',
    email: 'Email',
    grade: 'Grade',
    subject: 'Subject',
    actions: 'Actions',
    selectClass: 'Select Class',
    attention: 'Attention',
    participation: 'Participation',
    homework: 'Homework',
    behavior: 'Behavior',
    practice: 'Practice',
    scoreInput: 'Batch Score Input',
    generateInsight: 'Generate AI Insights',
    loading: 'Loading...',
    selectStudent: 'Select a student to view report',
    noData: 'No data available',
    view: 'View',
    // New Fields
    fullName: 'Full Name',
    englishName: 'English Name',
    chineseName: 'Chinese Name',
    phone: 'Phone Number',
    description: 'Description',
    school: 'School Name',
    parentName: 'Parent Name',
    relationship: 'Relationship',
    emergencyContact: 'Emergency Contact',
    parentEmail: 'Parent Email',
    parentDetails: 'Parent Details',
    // Locations
    addNewLocation: "Add New Location",
    locationName: "Location Name",
    locationNamePlaceholder: "e.g. Cheras Branch",
    address: "Address",
    addressPlaceholder: "e.g. 123 Jalan Damai",
    registeredClasses: "Registered Classes",
    deleteLocationConfirm: "Are you sure you want to delete this location?",
    locationRequired: "Cannot create class. Please add at least one location first.",
    assignedLocation: "Assigned Location",
    // Device Recommendations
    recommendDesktop: 'Recommended to use desktop view for HQ Admin tasks.',
    recommendMobile: 'Recommended to use mobile view for quick entry.',
    // Validation
    error: 'Error',
    teacherRequired: 'Cannot create class. Please add at least one teacher first.',
    classRequired: 'Cannot create student. Please create at least one class first.',
    addMock: 'Add Mock',
    // Dashboard & Reports
    dashboardOverview: "Overview of your institution's performance.",
    activeStudents: "Active students",
    noStudentData: "No students data",
    requiresAttention: "Requires immediate attention",
    avgAttendance: "Avg Attendance",
    classAverage: "Class average",
    performanceTrends: "Performance Trends",
    performanceTrendsDesc: "Average score improvement over time",
    studentsNeedingSupport: "Students needing support",
    criticalAttendance: "Critical Attendance",
    noStudentsAtRisk: "No students at risk.",
    activeCampuses: "Active Campuses",
    globalAverage: "Global Average",
    locationPerformanceOverview: "Location Performance Overview",
    sessionsMo: "Sessions (Mo)",
    studentDistribution: "Student Distribution",
    studentDistributionDesc: "Total headcount by location",
    institutionTrends: "Institution Performance Trends",
    institutionTrendsDesc: "6-Month view of Attendance vs Behavior Quality",
    behaviorAnalysis: "Behavioral Analysis",
    behaviorAnalysisDesc: "Average rating by category across all branches",
    hqAiSummary: "HQ AI Executive Summary",
    clickToAnalyze: "Click to analyze data...",
    locationReport: "Location Report",
    exportPDF: "Export PDF",
    branchTrend: "Branch Performance Trend (6 Months)",
    classComparison: "Class Performance Comparison",
    classBreakdown: "Class Detailed Breakdown",
    noClassesInLocation: "No classes found in this location.",
    viewReport: "View Report",
    // Teachers
    addNewTeacher: "Add New Teacher",
    autoFill: "Auto-Fill",
    fullNamePlaceholder: "Full Legal Name",
    englishNamePlaceholder: "e.g. Alice",
    chineseNamePlaceholder: "Chinese Name",
    emailPlaceholder_teacher: "teacher@example.com",
    phonePlaceholder: "+1 234 567 890",
    subjectPlaceholder: "e.g. Mathematics",
    descPlaceholder: "Brief bio or notes",
    deleteTeacherConfirm: "Are you sure you want to delete this teacher?",
    userCreated: "User account created with password '123'",
    hasAccount: "Has Account",
    noAccount: "No Account",
    // Students
    addNewStudent: "Add New Student",
    schoolPlaceholder: "e.g. City High School",
    guardianNamePlaceholder: "Guardian Name",
    parentInfo: "Parent Info",
    status: "Status",
    good: "Good",
    deleteStudentConfirm: "Are you sure you want to delete this student?",
    selectRelationship: "Select Relationship",
    father: "Father",
    mother: "Mother",
    guardian: "Guardian",
    other: "Other",
    manageClasses: "Manage Classes",
    enrolledClasses: "Enrolled Classes",
    selectClasses: "Select Classes",
    // Classes
    addNewClass: "Add New Class",
    className: "Class Name",
    classNamePlaceholder: "e.g. Grade 10 Math A",
    gradePlaceholder: "e.g. 10",
    assignedTeacher: "Assigned Teacher",
    unassigned: "Unassigned",
    deleteClassConfirm: "Are you sure you want to delete this class?",
    dayOfWeek: "Weekly Day",
    time: "Time",
    addSpecialSession: "Add Special Session",
    selectDay: "Select Day",
    // Sessions
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    sessionDate: "Date",
    sessionTime: "Time",
    sessionStudent: "Student (Optional)",
    allStudents: "All Students",
    sessionCreated: "Session Created",
    publicHoliday: "Public Holiday (Auto-Cancelled)",
    regular: "Regular",
    special: "Special",
    scheduled: "Scheduled",
    cancelled: "Cancelled",
    completed: "Completed",
    selectSession: "Select Session",
    sessionActive: "Start Class",
    sessionCancelledWarning: "This session is marked as cancelled.",
    postpone: "Postpone / Reschedule",
    selectMonthYear: "Select Month",
    startClass: "Start Class",
    rescheduleSession: "Reschedule Session",
    // Score Input
    addAssessmentColumn: "Add Assessment Column",
    columnName: "Column Name",
    columnNamePlaceholder: "e.g. Lab Report 1",
    editScores: "Edit Scores",
    saveScore: "Save Score",
    addCol: "Add Col",
    average: "Average",
    noClassesAvailable: "No Classes Available",
    createClassFirst: "Please ask Admin to create a Class first.",
    noStudentsInClass: "No students found in this class.",
    readingMode: "Reading Mode enabled. Switch to Edit to update scores.",
    score: "Score",
    // Class Rating
    ratingSubtitle: "Daily behavioral assessment.",
    complete: "Complete",
    pending: "Pending",
    studentOf: "Student",
    of: "/",
    present: "Present",
    absent: "Absent",
    reasonForAbsence: "Reason for Absence",
    selectReason: "Select Reason",
    tapToRate: "Tap to rate",
    rate: "Rate",
    selectCategory: "Select a category above",
    markAttendancePrompt: "Please mark attendance to proceed with rating.",
    markAsComplete: "Mark as Complete",
    nextStudent: "Next Student",
    ratingCompleteTitle: "Class Rating Complete!",
    ratingCompleteDesc: "You have successfully rated all students in",
    backToRatings: "Back to Ratings",
    classOverview: "Class Overview",
    rated: "Rated",
    sickLeave: "Sick Leave",
    personalLeave: "Personal Leave",
    schoolEvent: "School Event",
    unexcused: "Unexcused",
    date: "Date",
    sessionContext: "Session Details",
    // Student Report
    unknownClass: "Unknown Class",
    needsSupport: "Needs Support",
    simulatedReport: "Simulated: Report sent via WhatsApp",
    thinking: "Thinking...",
    analyzing: "Analyzing performance patterns...",
    scoreProgression: "Score Progression",
    scoreProgressionDesc: "Exam results over the last month",
    noScoreData: "No score data available",
    skillsBreakdown: "Skills Breakdown",
    skillsBreakdownDesc: "Holistic assessment of student capabilities",
    noStudentFound: "No student data found.",
    pleaseSelectStudent: "Please select a student.",
    sessionsSchedule: "Sessions Schedule",
    adminDetails: "Admin / Emergency Details",
    parentNameLabel: "PARENT NAME",
    emergencyContactLabel: "EMERGENCY CONTACT",
    parentEmailLabel: "PARENT EMAIL",
    aiAnalysis: "AI Analysis",
    classRatingTrend: "Class Rating Trend",
    behaviorBreakdown: "Behavior Breakdown",
    noSessionsFound: "No sessions found for this month.",
  },
  zh: {
    loginTitle: '登录 Insight EDU',
    emailPlaceholder: '邮箱地址',
    passwordPlaceholder: '密码',
    loginButton: '登录',
    loginFooter: '请使用下方演示账号。',
    forgotPassword: '忘记密码？',
    resetPassword: '重置密码',
    sendResetLink: '发送重置链接',
    backToLogin: '返回登录',
    resetSuccess: '如果该邮箱存在账号，您稍后将收到重置链接。',
    enterEmailForReset: '输入您的邮箱地址以重置密码。',
    logout: '退出登录',
    dashboard: '仪表盘',
    teachers: '教师管理',
    students: '学生管理',
    classes: '班级',
    locations: '地点管理',
    reports: '报告',
    input: '成绩录入',
    rating: '班级评分',
    hq: '总部管理',
    teacher: '教师端',
    parent: '家长端',
    atRisk: '需关注',
    totalStudents: '学生总数',
    avgPerformance: '平均表现',
    sendReport: '通过WhatsApp发送报告',
    sendReportEmail: '通过邮件发送报告',
    sendingReportEmail: '正在发送报告...',
    reportEmailSuccess: '报告邮件已发送。',
    reportEmailFailure: '报告邮件发送失败。',
    aiInsights: 'AI 智能分析',
    positiveTrend: '积极趋势',
    negativeTrend: '需要注意',
    overall: '综合总结',
    save: '保存',
    cancel: '取消',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    name: '姓名',
    email: '邮箱',
    grade: '年级',
    subject: '科目',
    actions: '操作',
    selectClass: '选择班级',
    attention: '专注度',
    participation: '参与度',
    homework: '作业',
    behavior: '行为',
    practice: '练习',
    scoreInput: '批量成绩录入',
    generateInsight: '生成 AI 分析',
    loading: '加载中...',
    selectStudent: '选择学生查看报告',
    noData: '暂无数据',
    view: '查看',
    // New Fields
    fullName: '全名',
    englishName: '英文名',
    chineseName: '中文名',
    phone: '电话号码',
    description: '描述',
    school: '学校名称',
    parentName: '家长姓名',
    relationship: '关系',
    emergencyContact: '紧急联系人',
    parentEmail: '家长邮箱',
    parentDetails: '家长详情',
    // Locations
    addNewLocation: "添加新地点",
    locationName: "地点名称",
    locationNamePlaceholder: "例如：蕉赖分校",
    address: "地址",
    addressPlaceholder: "例如：123 Jalan Damai",
    registeredClasses: "已注册班级",
    deleteLocationConfirm: "确定要删除这个地点吗？",
    locationRequired: "无法创建班级。请先添加至少一个地点。",
    assignedLocation: "分配地点",
    // Device Recommendations
    recommendDesktop: '建议使用桌面端进行总部管理操作。',
    recommendMobile: '建议使用移动端以便快速录入。',
    // Validation
    error: '错误',
    teacherRequired: '无法创建班级。请先添加至少一名教师。',
    classRequired: '无法创建学生。请先创建至少一个班级。',
    addMock: '添加模拟数据',
    // Dashboard & Reports
    dashboardOverview: "机构表现概览。",
    activeStudents: "在校学生",
    noStudentData: "暂无学生数据",
    requiresAttention: "需立即关注",
    avgAttendance: "平均出勤率",
    classAverage: "班级平均",
    performanceTrends: "成绩趋势",
    performanceTrendsDesc: "平均成绩随时间变化情况",
    studentsNeedingSupport: "需要支持的学生",
    criticalAttendance: "出勤率严重不足",
    noStudentsAtRisk: "暂无风险学生。",
    activeCampuses: "活跃校区",
    globalAverage: "全局平均",
    locationPerformanceOverview: "分校表现概览",
    sessionsMo: "本月课时",
    studentDistribution: "学生分布",
    studentDistributionDesc: "各分校学生总人数",
    institutionTrends: "机构表现趋势",
    institutionTrendsDesc: "过去6个月出勤率与行为质量趋势",
    behaviorAnalysis: "行为分析",
    behaviorAnalysisDesc: "各分校平均行为评分（按类别）",
    hqAiSummary: "总部 AI 执行摘要",
    clickToAnalyze: "点击分析数据...",
    locationReport: "分校报告",
    exportPDF: "导出 PDF",
    branchTrend: "分校表现趋势（6个月）",
    classComparison: "班级表现对比",
    classBreakdown: "班级详细数据",
    noClassesInLocation: "该分校暂无班级。",
    viewReport: "查看报告",
    // Teachers
    addNewTeacher: "添加新教师",
    autoFill: "自动填充",
    fullNamePlaceholder: "全名（法定姓名）",
    englishNamePlaceholder: "例如：Alice",
    chineseNamePlaceholder: "中文名",
    emailPlaceholder_teacher: "teacher@example.com",
    phonePlaceholder: "+1 234 567 890",
    subjectPlaceholder: "例如：数学",
    descPlaceholder: "简介或备注",
    deleteTeacherConfirm: "确定要删除这位教师吗？",
    userCreated: "已创建用户账号，密码 '123'",
    hasAccount: "有账号",
    noAccount: "无账号",
    // Students
    addNewStudent: "添加新学生",
    schoolPlaceholder: "例如：市第一中学",
    guardianNamePlaceholder: "监护人姓名",
    parentInfo: "家长信息",
    status: "状态",
    good: "良好",
    deleteStudentConfirm: "确定要删除这名学生吗？",
    selectRelationship: "选择关系",
    father: "父亲",
    mother: "母亲",
    guardian: "监护人",
    other: "其他",
    manageClasses: "管理班级",
    enrolledClasses: "已报班级",
    selectClasses: "选择班级",
    // Classes
    addNewClass: "添加新班级",
    className: "班级名称",
    classNamePlaceholder: "例如：十年级数学A班",
    gradePlaceholder: "例如：10",
    assignedTeacher: "负责教师",
    unassigned: "未分配",
    deleteClassConfirm: "确定要删除这个班级吗？",
    dayOfWeek: "每周上课日",
    time: "时间",
    addSpecialSession: "添加特殊课程",
    selectDay: "选择日期",
    // Sessions
    monday: "星期一",
    tuesday: "星期二",
    wednesday: "星期三",
    thursday: "星期四",
    friday: "星期五",
    saturday: "星期六",
    sunday: "星期日",
    sessionDate: "日期",
    sessionTime: "时间",
    sessionStudent: "学生 (可选)",
    allStudents: "所有学生",
    sessionCreated: "课程已创建",
    publicHoliday: "公共假期 (自动取消)",
    regular: "常规",
    special: "特殊",
    scheduled: "已安排",
    cancelled: "已取消",
    completed: "已完成",
    selectSession: "选择课程",
    sessionActive: "开始上课",
    sessionCancelledWarning: "此课程已标记为取消。",
    postpone: "延期 / 改期",
    selectMonthYear: "选择月份",
    startClass: "开始上课",
    rescheduleSession: "重新安排课程",
    // Score Input
    addAssessmentColumn: "添加评估列",
    columnName: "列名称",
    columnNamePlaceholder: "例如：实验报告 1",
    editScores: "编辑成绩",
    saveScore: "保存成绩",
    addCol: "添加列",
    average: "平均分",
    noClassesAvailable: "无可用班级",
    createClassFirst: "请联系管理员先创建班级。",
    noStudentsInClass: "该班级暂无学生。",
    readingMode: "已启用阅读模式。切换到编辑模式以更新成绩。",
    score: "分数",
    // Class Rating
    ratingSubtitle: "每日行为评估。",
    complete: "已完成",
    pending: "待处理",
    studentOf: "学生",
    of: "/",
    present: "出席",
    absent: "缺席",
    reasonForAbsence: "缺席原因",
    selectReason: "选择原因",
    tapToRate: "点击评分",
    rate: "评分",
    selectCategory: "请在上方选择一个类别",
    markAttendancePrompt: "请先标记出勤状态以继续评分。",
    markAsComplete: "标记为完成",
    nextStudent: "下一个学生",
    ratingCompleteTitle: "班级评分完成！",
    ratingCompleteDesc: "您已成功完成对以下班级所有学生的评分：",
    backToRatings: "返回评分",
    classOverview: "班级概览",
    rated: "已评",
    sickLeave: "病假",
    personalLeave: "事假",
    schoolEvent: "学校活动",
    unexcused: "无故缺席",
    date: "日期",
    sessionContext: "课程信息",
    // Student Report
    unknownClass: "未知班级",
    needsSupport: "需要支持",
    simulatedReport: "模拟：报告已通过 WhatsApp 发送",
    thinking: "思考中...",
    analyzing: "正在分析表现模式...",
    scoreProgression: "成绩进展",
    scoreProgressionDesc: "过去一个月的考试结果",
    noScoreData: "暂无成绩数据",
    skillsBreakdown: "技能细分",
    skillsBreakdownDesc: "学生能力的整体评估",
    noStudentFound: "未找到学生数据。",
    pleaseSelectStudent: "请选择一名学生。",
    sessionsSchedule: "课程安排",
    adminDetails: "管理员 / 紧急联系详情",
    parentNameLabel: "家长姓名",
    emergencyContactLabel: "紧急联系人",
    parentEmailLabel: "家长邮箱",
    aiAnalysis: "AI 智能分析",
    classRatingTrend: "班级评分趋势",
    behaviorBreakdown: "行为细分",
    noSessionsFound: "本月暂无课程。",
  }
};

// Helper to generate sessions (Logic)
export const generateScheduleSessions = (classId: string, dayOfWeek: string, time: string): Session[] => {
  const sessions: Session[] = [];
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const targetDayIndex = days.indexOf(dayOfWeek);
  
  if (targetDayIndex === -1) return [];

  let currentDate = new Date();
  // Find next occurrence of the day
  while (currentDate.getDay() !== targetDayIndex) {
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // Generate until end of 2029 (approx 5 years)
  const endDate = new Date('2029-12-31');
  let counter = 0;

  while (currentDate <= endDate) {
    const dateStr = currentDate.toISOString().split('T')[0];
    const isHoliday = PUBLIC_HOLIDAYS.includes(dateStr);
    
    sessions.push({
      id: `ses_${classId}_${counter}`,
      classId: classId,
      date: dateStr,
      startTime: time,
      type: 'REGULAR',
      status: isHoliday ? 'CANCELLED' : 'SCHEDULED'
    });

    // Next week
    currentDate.setDate(currentDate.getDate() + 7);
    counter++;
  }
  return sessions;
};
